[package]
name = "game-logic"
version = "0.1.0"
edition = "2024"

[features]
dynamic_linking = []
profiling = ["engine/profiling"]
puffin = ["dep:puffin", "engine/puffin"]
tracy = ["dep:tracy-client", "engine/tracy"]
renderdoc = ["engine/renderdoc"]

[dependencies]
engine = { path = "../../engine" }
game-types = { path = "../types" }
bytemuck = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
wgpu = { workspace = true }
pollster = { workspace = true }
libloading = { workspace = true }
rand = { workspace = true }
web-time = { workspace = true }
crossbeam-channel = { workspace = true }
image = { workspace = true }
subsecond = { workspace = true }
puffin = { workspace = true, optional = true }
tracy-client = { workspace = true, optional = true }

[lib]
crate-type = ["rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
