[package]
name = "engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["dylib"]

[dependencies]
anyhow = { workspace = true }
engine-inspector-derive = { path = "../engine_inspector_derive" }
winit = { workspace = true }
log = { workspace = true }
wgpu = { workspace = true }
pollster = { workspace = true }
bytemuck = { workspace = true }
half = { workspace = true }
cgmath = { workspace = true }
tobj = { workspace = true }
rand = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-log = { workspace = true }
tracy-client = { workspace = true, optional = true }
puffin = { workspace = true, optional = true }
ron = { workspace = true }
serde = { workspace = true }
bincode = { workspace = true }
uuid = { workspace = true }
offset-allocator = { workspace = true }
rapier3d = { workspace = true }
crossbeam-channel = { workspace = true }
num_cpus = { workspace = true }
parking_lot = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
renderdoc = { workspace = true }
libloading = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }
wgpu = { workspace = true, features = ["webgpu"] }
wasm-bindgen = { workspace = true }
wasm-bindgen-futures = { workspace = true }
web-sys = { workspace = true }
reqwest = { workspace = true }
getrandom = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
glob = "0.3"

[features]
renderdoc = []
profiling = []
tracy = [
    "profiling",
    "dep:tracy-client",
    "tracy-client/enable",
    "tracy-client/ondemand",
    "tracy-client/only-localhost",
]
puffin = ["profiling", "dep:puffin"]
