[package]
name = "game-runner"
version = "0.1.0"
edition = "2024"

[features]
default = ["static-game-logic", "profiling", "tracy"]
dynamic_linking = []
hot-reload = ["dep:hot-lib-reloader", "dynamic_linking"]
static-game-logic = ["dep:static-game-logic"]
renderdoc = ["engine/renderdoc"]
profiling = [
    "engine/profiling",
    "engine/puffin",
]
tracy = ["engine/tracy"]

[dependencies]
engine = { path = "../../engine" }
static-game-logic = { package = "game-logic", path = "../logic", optional = true }
game-types = { path = "../types" }
hot-lib-reloader = { workspace = true, optional = true }
winit = { workspace = true }
bytemuck = { workspace = true }
log = { workspace = true }
dioxus-devtools = { workspace = true }
