[package]
name = "editor-runner"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "editor-runner-bin"
path = "src/main.rs"

[features]
default = ["profiling", "tracy"]
dynamic_linking = [
    "dep:engine-dylib",
    "editor-logic/dynamic_linking",
    "game-logic/dynamic_linking",
]
hot-reload = ["dep:hot-lib-reloader", "dynamic_linking"]
profiling = [
    "engine/profiling",
    "engine/puffin",
    "engine-dylib?/profiling",
    "engine-dylib?/puffin",
    "editor-logic/puffin-ui",
]
tracy = ["engine/tracy", "engine-dylib?/tracy"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
game-logic = { path = "../../game/logic" }
editor-logic = { path = "../logic" }
engine-dylib = { path = "../../engine_dylib", optional = true }
anyhow = { workspace = true }
log = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
hot-lib-reloader = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
engine = { path = "../../engine", features = ["renderdoc"] }
egui-winit = "0.33.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
engine = { path = "../../engine" }
egui-winit = { version = "0.33.3", default-features = false }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
