[package]
name = "editor-runner"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "editor-runner-bin"
path = "src/main.rs"

[features]
default = ["static-game-logic", "profiling", "renderdoc"]
dynamic_linking = ["editor-logic/dynamic_linking"]
hot-reload = ["dep:hot-lib-reloader", "dynamic_linking"]
static-game-logic = ["dep:static-game-logic"]
profiling = [
    "engine/profiling",
    "engine/puffin",
    "editor-logic/puffin-ui",
    "static-game-logic?/profiling",
    "static-game-logic?/puffin",
]
tracy = ["engine/tracy", "editor-logic/tracy", "static-game-logic?/tracy"]
renderdoc = ["engine/renderdoc"]

[lib]
crate-type = ["rlib"]

[dependencies]
static-game-logic = { package = "game-logic", path = "../../game/logic", optional = true }
game-runner = { path = "../../game/runner", default-features = false }
editor-logic = { path = "../logic" }
anyhow = { workspace = true }
log = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
egui = { workspace = true }
egui-wgpu = { workspace = true }
hot-lib-reloader = { workspace = true, optional = true }
subsecond = { workspace = true }
dioxus-devtools = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
engine = { path = "../../engine" }
egui-winit = "0.33.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
engine = { path = "../../engine" }
egui-winit = { version = "0.33.3", default-features = false }
wasm-bindgen = { workspace = true }
console_error_panic_hook = { workspace = true }
console_log = { workspace = true }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
