[package]
name = "editor-logic"
version = "0.1.0"
edition = "2024"

[features]
dynamic_linking = []
puffin = ["dep:puffin", "engine/puffin"]
puffin-ui = ["puffin", "dep:puffin_egui"]
tracy = ["dep:tracy-client", "engine/tracy"]

[lib]
crate-type = ["rlib"]

[dependencies]
engine = { path = "../../engine" }
game-types = { path = "../../game/types" }
anyhow = { workspace = true }
log = { workspace = true }
winit = { workspace = true }
wgpu = { workspace = true }
egui = { workspace = true }
egui_dock = { workspace = true }
egui-wgpu = { workspace = true }
eframe = { workspace = true }
rfd = { workspace = true }
ron = { workspace = true }
serde = { workspace = true }
subsecond = { workspace = true }
puffin_egui = { workspace = true, optional = true }
puffin = { workspace = true, optional = true }
tracy-client = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
egui-winit = "0.33.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
egui-winit = { version = "0.33.3", default-features = false }
