[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"
rustflags = ["-Zshare-generics=n"]

[alias]
build-game = "build -p game-runner"
xtask = "run --package xtask --quiet --"
play = "xtask play"
play-editor = "xtask play-editor"
play-renderdoc = "xtask play-renderdoc"
play-wasm = "xtask play-wasm"
